server:
  port: 8002

dubbo:
  application:
    name: consumer

  registry:
    # 注册中心地址
    protocol: zookeeper
    address: 127.0.0.1:2181
    # 超时时间
    timeout: 60000
#    address: 224.5.6.7:1234
#    timeout: 60000
#    protocol: multicast